CREATE TYPE "public"."article_status" AS ENUM('published', 'draft', 'hidden');--> statement-breakpoint
CREATE TYPE "public"."popup_device" AS ENUM('all', 'pc', 'mobile');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'editor', 'reporter');--> statement-breakpoint
CREATE TYPE "public"."yn" AS ENUM('Y', 'N');--> statement-breakpoint
CREATE TABLE "articles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"board" varchar(32) DEFAULT 'news' NOT NULL,
	"title" varchar(500) NOT NULL,
	"subtitle" varchar(500),
	"reporter_name" varchar(100),
	"reporter_email" varchar(200),
	"section" varchar(50) DEFAULT '뉴스' NOT NULL,
	"region" varchar(50),
	"display_slot" varchar(50),
	"thumbnail_url" varchar(1000),
	"body_html" text NOT NULL,
	"body_text" text,
	"source" varchar(200),
	"source_url" varchar(1000),
	"tags" jsonb DEFAULT '[]'::jsonb,
	"view_count" integer DEFAULT 0 NOT NULL,
	"status" "article_status" DEFAULT 'published' NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "banners" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"position" varchar(50) NOT NULL,
	"image_url" varchar(1000) NOT NULL,
	"link_url" varchar(1000),
	"alt" varchar(255),
	"sort_order" integer DEFAULT 0 NOT NULL,
	"active" "yn" DEFAULT 'Y' NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "media_map" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_map_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"old_path" varchar(1000) NOT NULL,
	"r2_key" varchar(1000) NOT NULL,
	"r2_url" varchar(1000) NOT NULL,
	"bytes" integer,
	"content_type" varchar(100),
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "popups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "popups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255),
	"image_url" varchar(1000),
	"link_url" varchar(1000),
	"device" "popup_device" DEFAULT 'all' NOT NULL,
	"pos_x" integer DEFAULT 10 NOT NULL,
	"pos_y" integer DEFAULT 10 NOT NULL,
	"width" integer DEFAULT 400 NOT NULL,
	"height" integer DEFAULT 500 NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"active" "yn" DEFAULT 'Y' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "site_config" (
	"config_key" varchar(100) PRIMARY KEY NOT NULL,
	"config_value" text,
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(60) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"name" varchar(100) NOT NULL,
	"email" varchar(200),
	"role" "user_role" DEFAULT 'reporter' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE INDEX "section_idx" ON "articles" USING btree ("section");--> statement-breakpoint
CREATE INDEX "region_idx" ON "articles" USING btree ("region");--> statement-breakpoint
CREATE INDEX "slot_idx" ON "articles" USING btree ("display_slot");--> statement-breakpoint
CREATE INDEX "published_idx" ON "articles" USING btree ("published_at");--> statement-breakpoint
CREATE INDEX "status_idx" ON "articles" USING btree ("status");--> statement-breakpoint
CREATE INDEX "oldpath_idx" ON "media_map" USING btree ("old_path");