// 2차 기능 마이그레이션(정정·예약·구독·스니펫·스캔). 멱등.
import { neon } from "@neondatabase/serverless";
const sql = neon(process.env.DATABASE_URL_UNPOOLED || process.env.DATABASE_URL);

// enum 값 추가(ADD VALUE 는 트랜잭션 밖 단독 실행 필요 — neon http 는 autocommit)
await sql`ALTER TYPE article_status ADD VALUE IF NOT EXISTS 'scheduled'`;

await sql`ALTER TABLE articles ADD COLUMN IF NOT EXISTS correction_note varchar(500)`;
await sql`ALTER TABLE articles ADD COLUMN IF NOT EXISTS correction_at timestamptz`;

await sql`CREATE TABLE IF NOT EXISTS subscribers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  region varchar(50),
  confirmed_at timestamptz,
  unsubscribe_token varchar(64) NOT NULL,
  created_at timestamptz DEFAULT now()
)`;

await sql`CREATE TABLE IF NOT EXISTS snippets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label varchar(100) NOT NULL,
  html text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
)`;

await sql`CREATE TABLE IF NOT EXISTS scan_reports (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind varchar(30) NOT NULL,
  article_id integer,
  url varchar(1000),
  detail varchar(500),
  status varchar(20) NOT NULL DEFAULT 'open',
  created_at timestamptz DEFAULT now()
)`;
await sql`CREATE INDEX IF NOT EXISTS scan_kind_idx ON scan_reports(kind)`;
await sql`CREATE INDEX IF NOT EXISTS scan_status_idx ON scan_reports(status)`;

const enums = await sql`SELECT enumlabel FROM pg_enum e JOIN pg_type t ON e.enumtypid=t.oid WHERE t.typname='article_status' ORDER BY e.enumsortorder`;
const tbls = await sql`SELECT table_name FROM information_schema.tables WHERE table_name IN ('subscribers','snippets','scan_reports')`;
console.log("article_status 값:", enums.map((e) => e.enumlabel).join(", "));
console.log("신규 테이블:", tbls.map((t) => t.table_name).join(", "));
console.log("마이그레이션 2차 완료");
