// 접속자 통계·cron 헬스·SEO 메타 마이그레이션 (멱등). UNPOOLED 로 DDL 적용.
import { neon } from "@neondatabase/serverless";
const sql = neon(process.env.DATABASE_URL_UNPOOLED || process.env.DATABASE_URL);

await sql`ALTER TABLE articles ADD COLUMN IF NOT EXISTS meta_description varchar(300)`;
await sql`ALTER TABLE articles ADD COLUMN IF NOT EXISTS og_image varchar(1000)`;

await sql`CREATE TABLE IF NOT EXISTS page_views (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day date NOT NULL,
  path varchar(500) NOT NULL,
  article_id integer,
  visitor_hash varchar(64) NOT NULL,
  referrer_host varchar(255),
  device varchar(20),
  created_at timestamptz DEFAULT now()
)`;
await sql`CREATE INDEX IF NOT EXISTS pv_day_idx ON page_views(day)`;
await sql`CREATE INDEX IF NOT EXISTS pv_article_day_idx ON page_views(article_id, day)`;

await sql`CREATE TABLE IF NOT EXISTS cron_runs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at timestamptz DEFAULT now(),
  job varchar(50) NOT NULL DEFAULT 'gyeonggi-news',
  source_agency varchar(100) NOT NULL,
  fetched integer NOT NULL DEFAULT 0,
  published integer NOT NULL DEFAULT 0,
  skipped integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  error_text text
)`;
await sql`CREATE INDEX IF NOT EXISTS cron_runs_runat_idx ON cron_runs(run_at)`;

// 검증
const cols = await sql`SELECT column_name FROM information_schema.columns WHERE table_name='articles' AND column_name IN ('meta_description','og_image')`;
const tbls = await sql`SELECT table_name FROM information_schema.tables WHERE table_name IN ('page_views','cron_runs')`;
console.log("articles 신규 컬럼:", cols.map((c) => c.column_name).join(", "));
console.log("신규 테이블:", tbls.map((t) => t.table_name).join(", "));
console.log("마이그레이션 완료");
